name: "identity_fp32"
backend: "python"
platform: "custom"

input [
  {
    name: "IN"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]

output [
  {
    name: "OUT"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
