name: "batch_input_many_source0"
input [
  {
    name: "INPUT"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
batch_input [
  {
    kind: BATCH_ELEMENT_COUNT
    target_name: "BATCH_AND_SIZE_INPUT"
    data_type: TYPE_FP32
    source_input: ["INPUT", "INPUT"]
  }
]