name: "pytorch_simple"
backend: "pytorch"
max_batch_size: 8

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  },
  {
    name: "INPUT1"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  },
  {
    name: "OUTPUT1"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]