name: "vae"
platform: "tensorrt_plan"
max_batch_size: 8

input [
  {
    name: "latent_sample"
    data_type: TYPE_FP32
    dims: [ -1, -1, -1]
  }
]
output [
  {
    name: "sample"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]
