name: "control_type_bool"
platform: "onnxruntime_onnx"
max_batch_size: 8
version_policy: { latest { num_versions: 1 }}


instance_group [
  {
    kind: KIND_GPU
  }
]


input [
  {
    name: "INPUT"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    
    
  }
]
sequence_batching {
  max_sequence_idle_microseconds: 5000000
  control_input [
    {
      name: "START"
      control [
        {
          kind: CONTROL_SEQUENCE_START
          bool_false_true: [ 0, 1 ]
        }
      ]
    },
    {
      name: "READY"
      control [
        {
          kind: CONTROL_SEQUENCE_READY
          bool_false_true: [ 0, 1 ]
        }
      ]
    }
  ]
}
