name: "fp32_dim3_batch4"
max_batch_size: 4
backend: "identity"
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 16, 16, 16 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 16, 16, 16 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]
