#!/bin/bash
# Copyright 2019-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

############################################################################
## This script generates custom operations needed by some of the
## Triton's CI tests. Generating these custom operations requires
## using the TensorFlow container.
##
## 1. Update TENSORFLOW_IMAGE and PYTORCH_IMAGE to match what is being
## used by the Triton release being tested.
##
## 2. Run this script to create /tmp/qa_custom_ops.
##
############################################################################

TRITON_VERSION=${TRITON_VERSION:=25.02}
NVIDIA_UPSTREAM_VERSION=${NVIDIA_UPSTREAM_VERSION:=$TRITON_VERSION}
TENSORFLOW_IMAGE=${TENSORFLOW_IMAGE:=nvcr.io/nvidia/tensorflow:$NVIDIA_UPSTREAM_VERSION-tf2-py3}
PYTORCH_IMAGE=${PYTORCH_IMAGE:=nvcr.io/nvidia/pytorch:$NVIDIA_UPSTREAM_VERSION-py3}
UBUNTU_IMAGE=${UBUNTU_IMAGE:=ubuntu:24.04}

CUDA_DEVICE=${NV_GPU:=0}

DOCKER_GPU_ARGS=${DOCKER_GPU_ARGS:-$([[ $RUNNER_GPUS =~ ^[0-9] ]] && eval $NV_DOCKER_ARGS || echo "--gpus device=$CUDA_DEVICE" )}

############################################################################
# Check if Docker volume exists
############################################################################
CI_JOB_ID=${CI_JOB_ID:=$(date +%Y%m%d_%H%M)}
DOCKER_VOLUME=${DOCKER_VOLUME:=volume.gen_qa_custom_ops.${CI_JOB_ID}}
RUNNER_ID=${RUNNER_ID:=0}
PROJECT_NAME=${PROJECT_NAME:=tritonserver}
DOCKER_VOLUME_CONTAINER=${DOCKER_VOLUME}.gen_qa_custom_ops.${CI_JOB_ID}

if ! docker volume inspect $DOCKER_VOLUME > /dev/null 2>&1; then
    echo -e "\033[34m[ INFO ] - Docker volume $DOCKER_VOLUME does not exist. Creating... \033[0m "
    docker volume create $DOCKER_VOLUME --label RUNNER_ID=$RUNNER_ID --label PROJECT_NAME=$PROJECT_NAME
    docker volume inspect $DOCKER_VOLUME
else
    echo -e "\033[34m[ INFO ] - Docker volume in use: $DOCKER_VOLUME \033[0m "
    docker volume inspect $DOCKER_VOLUME
fi


docker run \
    --rm \
    --label RUNNER_ID=$RUNNER_ID \
    --label PROJECT_NAME=$PROJECT_NAME \
    -v $DOCKER_VOLUME:/mnt \
    -w /mnt/$CI_JOB_ID \
    $UBUNTU_IMAGE \
    mkdir -p gen_srcdir ${TRITON_VERSION}

docker create \
    --label RUNNER_ID=$RUNNER_ID \
    --label PROJECT_NAME=$PROJECT_NAME \
    --name $DOCKER_VOLUME_CONTAINER \
    -v $DOCKER_VOLUME:/mnt \
    -w /mnt/$CI_JOB_ID \
    $UBUNTU_IMAGE

docker cp . $DOCKER_VOLUME_CONTAINER:/mnt/$CI_JOB_ID/gen_srcdir

###
VOLUME_BUILD_DIR=${VOLUME_BUILD_DIR:=/mnt/$CI_JOB_ID}
VOLUME_SRCDIR=${VOLUME_SRCDIR:=$VOLUME_BUILD_DIR/gen_srcdir}
VOLUME_DESTDIR=$VOLUME_BUILD_DIR/$TRITON_VERSION/qa_custom_ops


docker run --rm -v $DOCKER_VOLUME:/mnt -w /mnt/$CI_JOB_ID $UBUNTU_IMAGE \
mkdir -p \
$VOLUME_DESTDIR/tf_custom_ops \
$VOLUME_DESTDIR/libtorch_custom_ops

TFSCRIPT=gen.TensorFlow.gen_qa_custom_ops.cmds
PYTSCRIPT=gen.PyTorch.gen_qa_custom_ops.cmds

# Tensorflow
# Set compilation option by "Select a particular C++ dialect."
[[ "${NVIDIA_UPSTREAM_VERSION}" < "22.10"  ]] && STD_FLAG="c++14" || STD_FLAG="c++17"

cat > $TFSCRIPT <<EOF
#!/bin/bash -x
# Make all generated files accessible outside of container
umask 0000
nvidia-smi -L || true
nvidia-smi || true
set -e

# Segmentation fault with protobuf 4.24.0 (https://github.com/tensorflow/tensorflow/issues/61551)
# Upgrade protobuf version to fix the issue.
pip3 install "protobuf>4.24.0"

TF_CFLAGS=\$(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))')
TF_LFLAGS=\$(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))')

# No CUDA
cd /tmp
cp /opt/tensorflow/tensorflow-source/tensorflow/examples/adding_an_op/zero_out_op_kernel_1.cc .
g++ -std=${STD_FLAG} -O2 -shared -fPIC zero_out_op_kernel_1.cc -o \$DESTDIR/libzeroout.so \${TF_CFLAGS[@]} \${TF_LFLAGS[@]}

# CUDA. Need to patch so that we can build it outside of bazel/TF
cp /opt/tensorflow/tensorflow-source/tensorflow/examples/adding_an_op/cuda_op_kernel.cc .
cp /opt/tensorflow/tensorflow-source/tensorflow/examples/adding_an_op/cuda_op_kernel.cu.cc .
patch -i $VOLUME_SRCDIR/cuda_op_kernel.cu.cc.patch cuda_op_kernel.cu.cc
nvcc --expt-relaxed-constexpr -std=${STD_FLAG} -O2 -c -arch=all -o cuda_op_kernel.cu.o cuda_op_kernel.cu.cc \${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
g++ -std=${STD_FLAG} -shared -o \$DESTDIR/libcudaop.so cuda_op_kernel.cc cuda_op_kernel.cu.o \${TF_CFLAGS[@]} -fPIC -L/usr/local/cuda/lib64 -lcudart \${TF_LFLAGS[@]}

cp $VOLUME_SRCDIR/busy_op_kernel.cc .
cp $VOLUME_SRCDIR/busy_op_kernel.cu.cc .
nvcc --expt-relaxed-constexpr -std=${STD_FLAG} -O2 -c -arch=all -o busy_op_kernel.cu.o busy_op_kernel.cu.cc \${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
g++ -std=${STD_FLAG} -shared -o \$DESTDIR/libbusyop.so busy_op_kernel.cc busy_op_kernel.cu.o \${TF_CFLAGS[@]} -fPIC -L/usr/local/cuda/lib64 -lcudart \${TF_LFLAGS[@]}

python3 $VOLUME_SRCDIR/gen_qa_custom_ops_models.py --graphdef --savedmodel \
    --models_dir=\$DESTDIR --zero_out_lib_path=\$DESTDIR/libzeroout.so \
    --cuda_op_lib_path=\$DESTDIR/libcudaop.so \
    --busy_op_lib_path=\$DESTDIR/libbusyop.so
chmod -R 777 \$DESTDIR
EOF

chmod a+x $TFSCRIPT
if [ $? -ne 0 ]; then
    echo -e "Failed: chmod"
    exit 1
fi

docker cp $TFSCRIPT $DOCKER_VOLUME_CONTAINER:$VOLUME_SRCDIR/$TFSCRIPT

docker pull $TENSORFLOW_IMAGE

echo -e "\033[34m[ INFO ] - Running:  $TFSCRIPT \033[0m "

docker run \
    --rm \
    --label RUNNER_ID=$RUNNER_ID \
    --label PROJECT_NAME=$PROJECT_NAME \
    $DOCKER_GPU_ARGS \
    -v $DOCKER_VOLUME:/mnt \
    -e DESTDIR=$VOLUME_DESTDIR/tf_custom_ops \
    $TENSORFLOW_IMAGE \
    bash -xe $VOLUME_SRCDIR/$TFSCRIPT

if [ $? -ne 0 ]; then
    echo -e "Failed"
    exit 1
fi

# PyTorch

cat > $PYTSCRIPT <<EOF
#!/bin/bash -x
# Make all generated files accessible outside of container
umask 0000
nvidia-smi -L || true
nvidia-smi || true
set -e
export TORCH_EXTENSIONS_DIR="/root/.cache/torch_extensions/"
python3 $VOLUME_SRCDIR/gen_qa_custom_ops_models.py --libtorch --models_dir=\$DESTDIR
cp \${TORCH_EXTENSIONS_DIR}/custom_modulo/custom_modulo.so \$DESTDIR/libtorch_modulo/.
chmod -R 777 \$DESTDIR
EOF

chmod a+x $PYTSCRIPT
if [ $? -ne 0 ]; then
    echo -e "Failed: chmod"
    exit 1
fi

docker cp $PYTSCRIPT $DOCKER_VOLUME_CONTAINER:$VOLUME_SRCDIR/$PYTSCRIPT

docker pull $PYTORCH_IMAGE

echo -e "\033[34m[ INFO ] - Running:  $PYTSCRIPT \033[0m "

docker run \
    --rm \
    --label RUNNER_ID=$RUNNER_ID \
    --label PROJECT_NAME=$PROJECT_NAME \
    $DOCKER_GPU_ARGS \
    -v $DOCKER_VOLUME:/mnt \
    -e DESTDIR=$VOLUME_DESTDIR/libtorch_custom_ops \
    $PYTORCH_IMAGE \
    bash -xe $VOLUME_SRCDIR/$PYTSCRIPT

if [ $? -ne 0 ]; then
    echo -e "Failed"
    exit 1
fi


if [ -z $CI ] ; then
    echo -e "\033[34m[ INFO ] - Copying generated models to /tmp/ \033[0m "
    docker cp $DOCKER_VOLUME_CONTAINER:$VOLUME_BUILD_DIR/$TRITON_VERSION /tmp/
    echo -e "\033[34m[ INFO ] - Removing Docker container $DOCKER_VOLUME_CONTAINER \033[0m "
    docker rm -f $(docker ps -a --filter volume=$DOCKER_VOLUME --format '{{ .ID }}')
    echo -e "\033[34m[ INFO ] - Removing Docker volume $DOCKER_VOLUME \033[0m "
    docker volume rm $DOCKER_VOLUME
fi