name: "text_recognition"
platform: "onnxruntime_onnx"
max_batch_size : 16
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 32, 100 ]
  }
]
output [
  {
    name: "308"
    data_type: TYPE_FP32
    dims: [ 26, 37 ]
  }
]

model_warmup {
   name: "text_recognition"
   batch_size: 16
   inputs: {
       key: "input.1"
       value: {
           data_type: TYPE_FP32
           dims: 1
           dims: 32
           dims: 100
           zero_data: true
       }
   }
}

optimization {
  graph : {
    level : 1
  }
 execution_accelerators {
    gpu_execution_accelerator : [ {
      name : "tensorrt",
      parameters { key: "precision_mode" value: "FP16" },
      parameters { key: "max_workspace_size_bytes" value: "1073741824" }
    }]
  }
}
