name: "instance_group_set"
max_batch_size: 8
platform: "ensemble"
ensemble_scheduling {
  step [
    {
      model_name: "model_a"
      model_version: -1
      input_map {
        key: "model_a_input"
        value: "data"
      }
      output_map {
        key: "model_a_output"
        value: "prob"
      }
    }
  ]
}
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "prob"
    data_type: TYPE_FP32
    dims: [ 10, 1, 1 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
    gpus: [ 42 ]
  }
]
