name: "identity_onnx_cache_off"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [ 1,1,2,2 ]
  }
]

output [
  {
    name: "y"
    data_type: TYPE_FP32
    dims: [ 1,1,2,2 ]
  }
]

instance_group [{ kind: KIND_CPU }]

response_cache {
  enable: False
}
