name: "reshape_zerodims1"
max_batch_size: 4
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2, 2 ]
    reshape { shape: [ 0 ] }
  }
]
