--- tensorflow_serving/util/net_http/server/public/BUILD	2018-11-01 12:04:22.185086318 -0700
+++ /home/david/dev/gitlab/dgx/tensorrtserver/tools/patch/tfs/util/net_http/server/public/BUILD	2018-11-02 11:47:57.254526547 -0700
@@ -2,8 +2,7 @@
 
 package(
     default_visibility = [
-        "//tensorflow_serving:internal",
-        "//tensorflow_serving/util/net_http:__subpackages__",
+        "//visibility:public",
     ],
 )
 
