ARG BASE_IMAGE=nvcr.io/nvidia/tritonserver:24.07-vllm-python-py3
FROM ${BASE_IMAGE}

RUN pip install /opt/tritonserver/python/*.whl

COPY requirements.txt requirements_vllm.txt /tmp
RUN pip install -r /tmp/requirements.txt && \
    pip install -r /tmp/requirements_vllm.txt
