ARG BASE_IMAGE=nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3
FROM ${BASE_IMAGE}

RUN pip install /opt/tritonserver/python/*.whl

COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt
