import tritonserver
from _typeshed import Incomplete as Incomplete

class KServeHttp:
    class Options:
        address: str
        port: int
        reuse_port: bool
        thread_count: int
        header_forward_pattern: str
    triton_frontend: Incomplete
    def __init__(self, server: tritonserver, options: KServeHttp.Options = None) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
