name: "circular_dependency_2"
max_batch_size: 2
platform: "ensemble"
ensemble_scheduling {
  step [
    {
      model_name: "circular_dependency"
      model_version: -1
      input_map {
        key: "data"
        value: "input"
      }
      output_map {
        key: "prob"
        value: "output"
      }
    }
  ]
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
