name: "fp32_dim1_batch2"
max_batch_size: 2
platform: "custom"
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]