name: "ensemble_identity_onnx_cache_off"
platform: "ensemble"
max_batch_size: 0
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [ 1,1,2,2 ]
  }
]
output [
  {
    name: "y"
    data_type: TYPE_FP32
    dims: [ 1,1,2,2 ]
  }
]

ensemble_scheduling {
  step [
    {
      model_name: "identity_onnx_cache_off"
      model_version: 1
      input_map {
        key: "x"
        value: "x"
      }
      output_map {
        key: "y"
        value: "step0_output0"
      }
    },
    {
      model_name: "identity_onnx_cache_off"
      model_version: 1
      input_map {
        key: "x"
        value: "step0_output0"
      }
      output_map {
        key: "y"
        value: "y"
      }
    }
  ]
}
