name: "priority_level1"
platform: "tensorflow_savedmodel"
max_batch_size: 8
dynamic_batching {
  priority_levels: 3
  default_priority_level: 2
  priority_queue_policy {
    key: 4
    value: {
    }
  }
}
input [
  {
    name: "INPUT"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
