# Copyright 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

include_guard(GLOBAL)

# Single-graph Conan resolution.
#
# Resolving one reference per `conan install` produces one dependency graph per
# call, and packages that appear in several graphs are resolved independently.
# That breaks in two ways:
#
#   1. CMakeDeps rewrites a config for every package in each graph, including
#      transitive ones, so a later resolve overwrites an earlier one's files.
#      Per-reference output folders fix that much.
#
#   2. Worse, two graphs then both provide the same CMake targets. Enabling GCS
#      pulled google-cloud-cpp, which depends on re2 and gRPC, so re2::re2 and
#      gRPC::* were claimed twice in one scope:
#
#        The link interface of target "re2::re2" contains:
#          CONAN_LIB::re2_re2_RELEASE   but the target was not found.
#
# Separate folders cannot fix (2): the collision is in CMake's target namespace,
# not on disk. Only a single graph can, because only then does Conan reconcile
# the shared packages to one version.
#
# The CLI cannot express that. Triton's gRPC is grpc/<v>@tritonserver/stable,
# a different reference from the grpc/<v> google-cloud-cpp requires, so Conan
# treats them as unrelated and keeps both. Reconciling them needs an explicit
# `override=True`, which only a conanfile can state -- hence the generated
# conanfile.py below.
#
# Usage:
#   triton_server_conan_graph_require(REF <ref> [OPTIONS ...] [OVERRIDE])
#   ... once per dependency ...
#   triton_server_conan_graph_resolve()      # one conan install for all of them

set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_REQUIRES "")
set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_OVERRIDES "")
set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_OPTIONS "")

# triton_server_conan_graph_require(REF <ref> [OPTIONS <o>...] [OVERRIDE])
#
# Record a reference for the single resolve. OVERRIDE marks it as replacing any
# other request for the same package name anywhere in the graph -- that is what
# makes every consumer of gRPC or re2 use Triton's build of them.
function(triton_server_conan_graph_require)
  cmake_parse_arguments(_g "OVERRIDE" "REF" "OPTIONS" ${ARGN})
  if(NOT _g_REF)
    message(FATAL_ERROR "triton_server_conan_graph_require requires REF")
  endif()

  get_property(_reqs GLOBAL PROPERTY TRITON_CONAN_GRAPH_REQUIRES)
  list(APPEND _reqs "${_g_REF}")
  set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_REQUIRES "${_reqs}")

  if(_g_OVERRIDE)
    get_property(_ovr GLOBAL PROPERTY TRITON_CONAN_GRAPH_OVERRIDES)
    list(APPEND _ovr "${_g_REF}")
    set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_OVERRIDES "${_ovr}")
  endif()

  if(_g_OPTIONS)
    get_property(_opts GLOBAL PROPERTY TRITON_CONAN_GRAPH_OPTIONS)
    list(APPEND _opts ${_g_OPTIONS})
    set_property(GLOBAL PROPERTY TRITON_CONAN_GRAPH_OPTIONS "${_opts}")
  endif()
endfunction()

# triton_server_conan_graph_resolve([<out_dir_var>])
#
# Write the collected references to a conanfile.py and resolve them in one pass.
# The generators folder is prepended to CMAKE_PREFIX_PATH so the subsequent
# find_package() calls bind to this single, self-consistent set.
function(triton_server_conan_graph_resolve)
  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] entered")

  get_property(_reqs GLOBAL PROPERTY TRITON_CONAN_GRAPH_REQUIRES)
  get_property(_ovr GLOBAL PROPERTY TRITON_CONAN_GRAPH_OVERRIDES)
  get_property(_opts GLOBAL PROPERTY TRITON_CONAN_GRAPH_OPTIONS)

  if(NOT _reqs)
    message(STATUS "[${CMAKE_CURRENT_FUNCTION}] done: nothing to resolve")
    return()
  endif()

  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] step 1/4: generating conanfile for ${_reqs}")
  set(_dir "${TRITON_SERVER_CONAN_OUTPUT_DIR}")
  file(MAKE_DIRECTORY "${_dir}")

  set(_body "from conan import ConanFile\n\n\n")
  string(APPEND _body "class TritonServerDeps(ConanFile):\n")
  string(APPEND _body "    # Generated by triton_server_conan_graph_resolve(); do not edit.\n")
  string(APPEND _body "    settings = \"os\", \"compiler\", \"build_type\", \"arch\"\n")
  string(APPEND _body "    generators = \"CMakeDeps\"\n\n")
  string(APPEND _body "    def requirements(self):\n")
  foreach(_r IN LISTS _reqs)
    if(_r IN_LIST _ovr)
      # force=True keeps this as a real requirement while also winning over any
      # other version of the same package in the graph -- which is what makes
      # google-cloud-cpp use Triton's gRPC instead of the grpc/1.54.3 its recipe
      # asks for. override=True would express only the override and not the
      # requirement, and stating both is rejected as a duplicate.
      string(APPEND _body "        self.requires(\"${_r}\", force=True)\n")
    else()
      string(APPEND _body "        self.requires(\"${_r}\")\n")
    endif()
  endforeach()
  file(WRITE "${_dir}/conanfile.py" "${_body}")

  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] step 2/4: assembling arguments")
  set(_args "")
  foreach(_o IN LISTS _opts)
    list(APPEND _args "-o" "${_o}")
  endforeach()
  if(CMAKE_BUILD_TYPE)
    list(APPEND _args "-s" "build_type=${CMAKE_BUILD_TYPE}")
  endif()
  if(TRITON_SERVER_CONAN_PROFILE)
    list(APPEND _args "-pr:h" "${TRITON_SERVER_CONAN_PROFILE}"
                      "-pr:b" "${TRITON_SERVER_CONAN_PROFILE}")
  endif()

  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] step 3/4: resolving all references in one graph")
  find_program(TRITON_SERVER_CONAN_EXECUTABLE NAMES conan REQUIRED)
  execute_process(
    COMMAND "${TRITON_SERVER_CONAN_EXECUTABLE}" install "${_dir}/conanfile.py"
            ${_args} --output-folder=${_dir} --build=missing
    RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out
    ERROR_VARIABLE _err)

  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR
      "Single-graph conan install failed (exit ${_rc}).\n"
      "References: ${_reqs}\n"
      "--- stderr ---\n${_err}")
  endif()

  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] step 4/4: extending CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH")
  list(PREPEND CMAKE_PREFIX_PATH "${_dir}")
  list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)
  set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)

  # CMAKE_MODULE_PATH matters as much as CMAKE_PREFIX_PATH. CMakeDeps emits a
  # Find<Pkg>.cmake for any package consumed in module mode -- OpenSSL and
  # Protobuf among them -- and without this CMake silently falls back to its own
  # FindOpenSSL, which defines OpenSSL::SSL and OpenSSL::Crypto but not the
  # package-level openssl::openssl that libevent's generated config references:
  #
  #   The link interface of target "libevent_libevent_openssl_DEPS_TARGET"
  #   contains: openssl::openssl   but the target was not found.
  #
  # The failure surfaces at generate time, well away from the find_package call
  # that caused it.
  list(PREPEND CMAKE_MODULE_PATH "${_dir}")
  list(REMOVE_DUPLICATES CMAKE_MODULE_PATH)
  set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}" PARENT_SCOPE)

  if(ARGC GREATER 0)
    set(${ARGV0} "${_dir}" PARENT_SCOPE)
  endif()
  message(STATUS "[${CMAKE_CURRENT_FUNCTION}] done: one graph, ${_dir}")
endfunction()
