backend: "python"
max_batch_size: 64

input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ -1, 384 ]
  }
]

instance_group [
  {
    count: 1
    kind : KIND_CPU
  }
]
