--- tensorflow_serving/util/BUILD	2018-11-01 12:04:22.185086318 -0700
+++ /home/david/dev/gitlab/dgx/tensorrtserver/tools/patch/tfs/util/BUILD	2018-11-02 11:47:57.254526547 -0700
@@ -2,7 +2,7 @@
 
 package(
     default_visibility = [
-        "//tensorflow_serving:internal",
+        "//visibility:public",
     ],
     features = ["-layering_check"],
 )
